# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SOFIACruiseDirectorPanel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 814)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 814))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 240))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txt_ttl = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(50)
        self.txt_ttl.setFont(font)
        self.txt_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_ttl.setObjectName("txt_ttl")
        self.gridLayout_7.addWidget(self.txt_ttl, 1, 0, 1, 3)
        self.set_takeoff_time = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_takeoff_time.sizePolicy().hasHeightForWidth())
        self.set_takeoff_time.setSizePolicy(sizePolicy)
        self.set_takeoff_time.setObjectName("set_takeoff_time")
        self.gridLayout_7.addWidget(self.set_takeoff_time, 2, 0, 1, 1)
        self.txt_met = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(50)
        self.txt_met.setFont(font)
        self.txt_met.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_met.setObjectName("txt_met")
        self.gridLayout_7.addWidget(self.txt_met, 0, 0, 1, 3)
        self.set_landing_time = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_landing_time.sizePolicy().hasHeightForWidth())
        self.set_landing_time.setSizePolicy(sizePolicy)
        self.set_landing_time.setCheckable(False)
        self.set_landing_time.setFlat(False)
        self.set_landing_time.setObjectName("set_landing_time")
        self.gridLayout_7.addWidget(self.set_landing_time, 2, 1, 1, 1)
        self.set_takeoff_landing = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_takeoff_landing.sizePolicy().hasHeightForWidth())
        self.set_takeoff_landing.setSizePolicy(sizePolicy)
        self.set_takeoff_landing.setObjectName("set_takeoff_landing")
        self.gridLayout_7.addWidget(self.set_takeoff_landing, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 7, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.setup_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setup_button.sizePolicy().hasHeightForWidth())
        self.setup_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.setup_button.setFont(font)
        self.setup_button.setObjectName("setup_button")
        self.verticalLayout_2.addWidget(self.setup_button)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        self.end_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_button.sizePolicy().hasHeightForWidth())
        self.end_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.end_button.setFont(font)
        self.end_button.setObjectName("end_button")
        self.verticalLayout_2.addWidget(self.end_button)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(15, 30, 1226, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.directorLogTab = QtWidgets.QWidget()
        self.directorLogTab.setObjectName("directorLogTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.directorLogTab)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.log_takeoff = QtWidgets.QPushButton(self.directorLogTab)
        self.log_takeoff.setObjectName("log_takeoff")
        self.gridLayout_10.addWidget(self.log_takeoff, 0, 0, 1, 1)
        self.log_on_heading = QtWidgets.QPushButton(self.directorLogTab)
        self.log_on_heading.setObjectName("log_on_heading")
        self.gridLayout_10.addWidget(self.log_on_heading, 0, 1, 1, 1)
        self.log_post = QtWidgets.QPushButton(self.directorLogTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_post.sizePolicy().hasHeightForWidth())
        self.log_post.setSizePolicy(sizePolicy)
        self.log_post.setObjectName("log_post")
        self.gridLayout_10.addWidget(self.log_post, 2, 9, 1, 1)
        self.log_input_line = QtWidgets.QLineEdit(self.directorLogTab)
        self.log_input_line.setObjectName("log_input_line")
        self.gridLayout_10.addWidget(self.log_input_line, 2, 0, 1, 9)
        self.log_display = QtWidgets.QTextEdit(self.directorLogTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_display.sizePolicy().hasHeightForWidth())
        self.log_display.setSizePolicy(sizePolicy)
        self.log_display.setReadOnly(True)
        self.log_display.setObjectName("log_display")
        self.gridLayout_10.addWidget(self.log_display, 1, 0, 1, 10)
        self.log_on_target = QtWidgets.QPushButton(self.directorLogTab)
        self.log_on_target.setObjectName("log_on_target")
        self.gridLayout_10.addWidget(self.log_on_target, 0, 2, 1, 1)
        self.log_turning = QtWidgets.QPushButton(self.directorLogTab)
        self.log_turning.setObjectName("log_turning")
        self.gridLayout_10.addWidget(self.log_turning, 0, 3, 1, 1)
        self.log_fault_mccs = QtWidgets.QPushButton(self.directorLogTab)
        self.log_fault_mccs.setObjectName("log_fault_mccs")
        self.gridLayout_10.addWidget(self.log_fault_mccs, 0, 4, 1, 1)
        self.log_fault_si = QtWidgets.QPushButton(self.directorLogTab)
        self.log_fault_si.setObjectName("log_fault_si")
        self.gridLayout_10.addWidget(self.log_fault_si, 0, 5, 1, 1)
        self.log_landing = QtWidgets.QPushButton(self.directorLogTab)
        self.log_landing.setObjectName("log_landing")
        self.gridLayout_10.addWidget(self.log_landing, 0, 6, 1, 1)
        self.log_ignore = QtWidgets.QPushButton(self.directorLogTab)
        self.log_ignore.setObjectName("log_ignore")
        self.gridLayout_10.addWidget(self.log_ignore, 0, 7, 1, 1)
        self.tabWidget.addTab(self.directorLogTab, "")
        self.dataLogTab = QtWidgets.QWidget()
        self.dataLogTab.setObjectName("dataLogTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dataLogTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_data_log = QtWidgets.QTableWidget(self.dataLogTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_data_log.sizePolicy().hasHeightForWidth())
        self.table_data_log.setSizePolicy(sizePolicy)
        self.table_data_log.setMinimumSize(QtCore.QSize(0, 200))
        self.table_data_log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_data_log.setAlternatingRowColors(True)
        self.table_data_log.setObjectName("table_data_log")
        self.table_data_log.setColumnCount(0)
        self.table_data_log.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_data_log, 8, 0, 2, 4)
        self.widget_5 = QtWidgets.QWidget(self.dataLogTab)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.data_log_update_interval = QtWidgets.QSpinBox(self.widget_5)
        self.data_log_update_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.data_log_update_interval.setProperty("value", 5)
        self.data_log_update_interval.setObjectName("data_log_update_interval")
        self.gridLayout_12.addWidget(self.data_log_update_interval, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_5, 2, 1, 1, 1)
        self.data_log_autoupdate = QtWidgets.QCheckBox(self.dataLogTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_log_autoupdate.sizePolicy().hasHeightForWidth())
        self.data_log_autoupdate.setSizePolicy(sizePolicy)
        self.data_log_autoupdate.setChecked(True)
        self.data_log_autoupdate.setObjectName("data_log_autoupdate")
        self.gridLayout_3.addWidget(self.data_log_autoupdate, 2, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.dataLogTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.data_log_edit_keywords = QtWidgets.QPushButton(self.widget_6)
        self.data_log_edit_keywords.setObjectName("data_log_edit_keywords")
        self.gridLayout_14.addWidget(self.data_log_edit_keywords, 0, 4, 1, 1)
        self.data_log_flag_file = QtWidgets.QPushButton(self.widget_6)
        self.data_log_flag_file.setObjectName("data_log_flag_file")
        self.gridLayout_14.addWidget(self.data_log_flag_file, 0, 1, 1, 1)
        self.data_log_add_row = QtWidgets.QPushButton(self.widget_6)
        self.data_log_add_row.setObjectName("data_log_add_row")
        self.gridLayout_14.addWidget(self.data_log_add_row, 0, 2, 1, 1)
        self.data_log_delete_row = QtWidgets.QPushButton(self.widget_6)
        self.data_log_delete_row.setObjectName("data_log_delete_row")
        self.gridLayout_14.addWidget(self.data_log_delete_row, 0, 3, 1, 1)
        self.data_log_force_update = QtWidgets.QPushButton(self.widget_6)
        self.data_log_force_update.setObjectName("data_log_force_update")
        self.gridLayout_14.addWidget(self.data_log_force_update, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_6, 10, 0, 1, 4)
        self.tabWidget.addTab(self.dataLogTab, "")
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 9)
        self.TimesWorld = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesWorld.sizePolicy().hasHeightForWidth())
        self.TimesWorld.setSizePolicy(sizePolicy)
        self.TimesWorld.setMaximumSize(QtCore.QSize(16777215, 175))
        self.TimesWorld.setObjectName("TimesWorld")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TimesWorld)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_local_time = QtWidgets.QLabel(self.TimesWorld)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_local_time.sizePolicy().hasHeightForWidth())
        self.txt_local_time.setSizePolicy(sizePolicy)
        self.txt_local_time.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(50)
        self.txt_local_time.setFont(font)
        self.txt_local_time.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_local_time.setObjectName("txt_local_time")
        self.gridLayout_5.addWidget(self.txt_local_time, 2, 0, 1, 1)
        self.txt_utc = QtWidgets.QLabel(self.TimesWorld)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_utc.sizePolicy().hasHeightForWidth())
        self.txt_utc.setSizePolicy(sizePolicy)
        self.txt_utc.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(50)
        self.txt_utc.setFont(font)
        self.txt_utc.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_utc.setObjectName("txt_utc")
        self.gridLayout_5.addWidget(self.txt_utc, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.TimesWorld, 2, 7, 1, 1)
        self.LegInformation = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegInformation.sizePolicy().hasHeightForWidth())
        self.LegInformation.setSizePolicy(sizePolicy)
        self.LegInformation.setMinimumSize(QtCore.QSize(0, 175))
        self.LegInformation.setMaximumSize(QtCore.QSize(16777215, 175))
        self.LegInformation.setObjectName("LegInformation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.LegInformation)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.LegInformation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.set_landing_fp = QtWidgets.QCheckBox(self.widget_3)
        self.set_landing_fp.setGeometry(QtCore.QRect(0, 52, 158, 20))
        self.set_landing_fp.setChecked(True)
        self.set_landing_fp.setObjectName("set_landing_fp")
        self.set_takeoff_fp = QtWidgets.QCheckBox(self.widget_3)
        self.set_takeoff_fp.setGeometry(QtCore.QRect(0, 0, 155, 21))
        self.set_takeoff_fp.setChecked(True)
        self.set_takeoff_fp.setObjectName("set_takeoff_fp")
        self.leg_details = QtWidgets.QWidget(self.widget_3)
        self.leg_details.setGeometry(QtCore.QRect(190, 0, 311, 141))
        self.leg_details.setObjectName("leg_details")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.leg_details)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.leg_obs_block = QtWidgets.QLabel(self.leg_details)
        self.leg_obs_block.setText("")
        self.leg_obs_block.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.leg_obs_block.setObjectName("leg_obs_block")
        self.gridLayout_6.addWidget(self.leg_obs_block, 4, 1, 1, 1)
        self.leg_rof_rof_rate = QtWidgets.QLabel(self.leg_details)
        self.leg_rof_rof_rate.setText("")
        self.leg_rof_rof_rate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.leg_rof_rof_rate.setObjectName("leg_rof_rof_rate")
        self.gridLayout_6.addWidget(self.leg_rof_rof_rate, 3, 1, 1, 1)
        self.txt_elevation = QtWidgets.QLabel(self.leg_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_elevation.sizePolicy().hasHeightForWidth())
        self.txt_elevation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_elevation.setFont(font)
        self.txt_elevation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_elevation.setObjectName("txt_elevation")
        self.gridLayout_6.addWidget(self.txt_elevation, 2, 0, 1, 1)
        self.leg_target = QtWidgets.QLabel(self.leg_details)
        self.leg_target.setText("")
        self.leg_target.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.leg_target.setObjectName("leg_target")
        self.gridLayout_6.addWidget(self.leg_target, 1, 1, 1, 1)
        self.leg_number = QtWidgets.QLabel(self.leg_details)
        self.leg_number.setText("")
        self.leg_number.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.leg_number.setObjectName("leg_number")
        self.gridLayout_6.addWidget(self.leg_number, 0, 1, 1, 1)
        self.txt_rof = QtWidgets.QLabel(self.leg_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_rof.sizePolicy().hasHeightForWidth())
        self.txt_rof.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_rof.setFont(font)
        self.txt_rof.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_rof.setObjectName("txt_rof")
        self.gridLayout_6.addWidget(self.txt_rof, 3, 0, 1, 1)
        self.txt_obs_plan = QtWidgets.QLabel(self.leg_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_obs_plan.sizePolicy().hasHeightForWidth())
        self.txt_obs_plan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_obs_plan.setFont(font)
        self.txt_obs_plan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_obs_plan.setObjectName("txt_obs_plan")
        self.gridLayout_6.addWidget(self.txt_obs_plan, 4, 0, 1, 1)
        self.leg_elevation = QtWidgets.QLabel(self.leg_details)
        self.leg_elevation.setText("")
        self.leg_elevation.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.leg_elevation.setObjectName("leg_elevation")
        self.gridLayout_6.addWidget(self.leg_elevation, 2, 1, 1, 1)
        self.txt_target = QtWidgets.QLabel(self.leg_details)
        self.txt_target.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_target.sizePolicy().hasHeightForWidth())
        self.txt_target.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_target.setFont(font)
        self.txt_target.setLineWidth(1)
        self.txt_target.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_target.setObjectName("txt_target")
        self.gridLayout_6.addWidget(self.txt_target, 1, 0, 1, 1)
        self.txt_leg = QtWidgets.QLabel(self.leg_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_leg.sizePolicy().hasHeightForWidth())
        self.txt_leg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_leg.setFont(font)
        self.txt_leg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_leg.setObjectName("txt_leg")
        self.gridLayout_6.addWidget(self.txt_leg, 0, 0, 1, 1)
        self.takeoff_time = QtWidgets.QDateTimeEdit(self.widget_3)
        self.takeoff_time.setGeometry(QtCore.QRect(0, 22, 159, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeoff_time.sizePolicy().hasHeightForWidth())
        self.takeoff_time.setSizePolicy(sizePolicy)
        self.takeoff_time.setAlignment(QtCore.Qt.AlignCenter)
        self.takeoff_time.setObjectName("takeoff_time")
        self.landing_time = QtWidgets.QDateTimeEdit(self.widget_3)
        self.landing_time.setGeometry(QtCore.QRect(0, 72, 159, 21))
        self.landing_time.setAlignment(QtCore.Qt.AlignCenter)
        self.landing_time.setObjectName("landing_time")
        self.leg_previous = QtWidgets.QPushButton(self.widget_3)
        self.leg_previous.setGeometry(QtCore.QRect(0, 100, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_previous.sizePolicy().hasHeightForWidth())
        self.leg_previous.setSizePolicy(sizePolicy)
        self.leg_previous.setObjectName("leg_previous")
        self.leg_next = QtWidgets.QPushButton(self.widget_3)
        self.leg_next.setGeometry(QtCore.QRect(110, 100, 80, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_next.sizePolicy().hasHeightForWidth())
        self.leg_next.setSizePolicy(sizePolicy)
        self.leg_next.setObjectName("leg_next")
        self.set_landing_fp.raise_()
        self.set_takeoff_fp.raise_()
        self.leg_details.raise_()
        self.takeoff_time.raise_()
        self.landing_time.raise_()
        self.leg_next.raise_()
        self.leg_previous.raise_()
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.LegInformation, 2, 0, 1, 7)
        self.setup_info = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setup_info.sizePolicy().hasHeightForWidth())
        self.setup_info.setSizePolicy(sizePolicy)
        self.setup_info.setMinimumSize(QtCore.QSize(0, 240))
        self.setup_info.setObjectName("setup_info")
        self.layoutWidget = QtWidgets.QWidget(self.setup_info)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.flight_plan_filename = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.flight_plan_filename.setFont(font)
        self.flight_plan_filename.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flight_plan_filename.setObjectName("flight_plan_filename")
        self.verticalLayout_3.addWidget(self.flight_plan_filename)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.txt_log_output_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.txt_log_output_name.setFont(font)
        self.txt_log_output_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_log_output_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_log_output_name.setObjectName("txt_log_output_name")
        self.verticalLayout_3.addWidget(self.txt_log_output_name)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.txt_data_log_save_file = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.txt_data_log_save_file.setFont(font)
        self.txt_data_log_save_file.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_data_log_save_file.setObjectName("txt_data_log_save_file")
        self.verticalLayout_3.addWidget(self.txt_data_log_save_file)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.txt_data_log_dir = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.txt_data_log_dir.setFont(font)
        self.txt_data_log_dir.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_data_log_dir.setObjectName("txt_data_log_dir")
        self.verticalLayout_3.addWidget(self.txt_data_log_dir)
        self.instrument_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instrument_label.setFont(font)
        self.instrument_label.setObjectName("instrument_label")
        self.verticalLayout_3.addWidget(self.instrument_label)
        self.instrument_text = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.instrument_text.setFont(font)
        self.instrument_text.setObjectName("instrument_text")
        self.verticalLayout_3.addWidget(self.instrument_text)
        self.gridLayout.addWidget(self.setup_info, 1, 1, 1, 6)
        self.LegTimers = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LegTimers.sizePolicy().hasHeightForWidth())
        self.LegTimers.setSizePolicy(sizePolicy)
        self.LegTimers.setMaximumSize(QtCore.QSize(16777215, 420))
        self.LegTimers.setObjectName("LegTimers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.LegTimers)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_leg_timer = QtWidgets.QLabel(self.LegTimers)
        font = QtGui.QFont()
        font.setFamily("Digital-7")
        font.setPointSize(45)
        self.txt_leg_timer.setFont(font)
        self.txt_leg_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_leg_timer.setObjectName("txt_leg_timer")
        self.gridLayout_2.addWidget(self.txt_leg_timer, 1, 0, 2, 1)
        self.widget = QtWidgets.QWidget(self.LegTimers)
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.leg_timer_stop = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_timer_stop.sizePolicy().hasHeightForWidth())
        self.leg_timer_stop.setSizePolicy(sizePolicy)
        self.leg_timer_stop.setObjectName("leg_timer_stop")
        self.gridLayout_8.addWidget(self.leg_timer_stop, 0, 1, 1, 1)
        self.leg_timer_start = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_timer_start.sizePolicy().hasHeightForWidth())
        self.leg_timer_start.setSizePolicy(sizePolicy)
        self.leg_timer_start.setObjectName("leg_timer_start")
        self.gridLayout_8.addWidget(self.leg_timer_start, 0, 0, 1, 1)
        self.sub_minute = QtWidgets.QPushButton(self.widget)
        self.sub_minute.setObjectName("sub_minute")
        self.gridLayout_8.addWidget(self.sub_minute, 2, 1, 1, 1)
        self.add_minute = QtWidgets.QPushButton(self.widget)
        self.add_minute.setObjectName("add_minute")
        self.gridLayout_8.addWidget(self.add_minute, 2, 0, 1, 1)
        self.leg_timer_reset = QtWidgets.QPushButton(self.widget)
        self.leg_timer_reset.setObjectName("leg_timer_reset")
        self.gridLayout_8.addWidget(self.leg_timer_reset, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget, 4, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.LegTimers)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.time_select_remaining = QtWidgets.QRadioButton(self.widget_2)
        self.time_select_remaining.setChecked(True)
        self.time_select_remaining.setObjectName("time_select_remaining")
        self.gridLayout_9.addWidget(self.time_select_remaining, 0, 0, 1, 1)
        self.time_select_elapsed = QtWidgets.QRadioButton(self.widget_2)
        self.time_select_elapsed.setChecked(False)
        self.time_select_elapsed.setObjectName("time_select_elapsed")
        self.gridLayout_9.addWidget(self.time_select_elapsed, 0, 1, 1, 1)
        self.leg_duration = QtWidgets.QTimeEdit(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leg_duration.setFont(font)
        self.leg_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.leg_duration.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.leg_duration.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.leg_duration.setTimeSpec(QtCore.Qt.LocalTime)
        self.leg_duration.setObjectName("leg_duration")
        self.gridLayout_9.addWidget(self.leg_duration, 3, 0, 1, 2)
        self.txt_leg_duration = QtWidgets.QLabel(self.widget_2)
        self.txt_leg_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_leg_duration.setObjectName("txt_leg_duration")
        self.gridLayout_9.addWidget(self.txt_leg_duration, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.LegTimers)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 311, 38))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.leg_start_from_mis = QtWidgets.QLabel(self.layoutWidget1)
        self.leg_start_from_mis.setText("")
        self.leg_start_from_mis.setObjectName("leg_start_from_mis")
        self.gridLayout_11.addWidget(self.leg_start_from_mis, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 1, 0, 1, 1)
        self.leg_dur_from_mis = QtWidgets.QLabel(self.layoutWidget1)
        self.leg_dur_from_mis.setText("")
        self.leg_dur_from_mis.setObjectName("leg_dur_from_mis")
        self.gridLayout_11.addWidget(self.leg_dur_from_mis, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.LegTimers, 1, 8, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFIA Science Cruise Director"))
        self.groupBox.setTitle(_translate("MainWindow", "Current Flight Progress"))
        self.txt_ttl.setText(_translate("MainWindow", "TTL"))
        self.set_takeoff_time.setText(_translate("MainWindow", "Start MET"))
        self.txt_met.setText(_translate("MainWindow", "MET"))
        self.set_landing_time.setText(_translate("MainWindow", "Start TTL"))
        self.set_takeoff_landing.setText(_translate("MainWindow", "Start Both"))
        self.setup_button.setText(_translate("MainWindow", "Set Up"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.end_button.setText(_translate("MainWindow", "End"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Logging"))
        self.log_takeoff.setText(_translate("MainWindow", "Takeoff"))
        self.log_on_heading.setText(_translate("MainWindow", "On Heading"))
        self.log_post.setText(_translate("MainWindow", "Post"))
        self.log_display.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Lucida Grande UI\'; font-size:13pt;\"><br /></p></body></html>"))
        self.log_on_target.setText(_translate("MainWindow", "On Target"))
        self.log_turning.setText(_translate("MainWindow", "Turning"))
        self.log_fault_mccs.setText(_translate("MainWindow", "MCCS Problem"))
        self.log_fault_si.setText(_translate("MainWindow", "SI Problem"))
        self.log_landing.setText(_translate("MainWindow", "Landing"))
        self.log_ignore.setText(_translate("MainWindow", "Ignore Last Line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.directorLogTab), _translate("MainWindow", "Cruise Director Log"))
        self.data_log_update_interval.setSuffix(_translate("MainWindow", " seconds"))
        self.data_log_autoupdate.setText(_translate("MainWindow", "Autoupdate every:"))
        self.data_log_edit_keywords.setText(_translate("MainWindow", "Edit Keywords ..."))
        self.data_log_flag_file.setText(_translate("MainWindow", "Flag File"))
        self.data_log_add_row.setText(_translate("MainWindow", "Add a Blank Row"))
        self.data_log_delete_row.setText(_translate("MainWindow", "Remove Highlighted Row"))
        self.data_log_force_update.setText(_translate("MainWindow", "Force Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataLogTab), _translate("MainWindow", "Data Log"))
        self.TimesWorld.setTitle(_translate("MainWindow", "World Times "))
        self.txt_local_time.setText(_translate("MainWindow", "LOCAL"))
        self.txt_utc.setText(_translate("MainWindow", "UTC"))
        self.LegInformation.setTitle(_translate("MainWindow", "Flight Plan Information"))
        self.set_landing_fp.setText(_translate("MainWindow", "Set Landing from Plan"))
        self.set_takeoff_fp.setText(_translate("MainWindow", "Set Takeoff from Plan"))
        self.txt_elevation.setText(_translate("MainWindow", "Elevation Range:"))
        self.txt_rof.setText(_translate("MainWindow", "ROF | ROFrate:"))
        self.txt_obs_plan.setText(_translate("MainWindow", "ObsPlan:"))
        self.txt_target.setText(_translate("MainWindow", "Target:"))
        self.txt_leg.setText(_translate("MainWindow", "Leg:"))
        self.takeoff_time.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy HH:mm:ss"))
        self.landing_time.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy HH:mm:ss"))
        self.leg_previous.setText(_translate("MainWindow", "Previous Leg"))
        self.leg_previous.setShortcut(_translate("MainWindow", "<, Ctrl+N"))
        self.leg_next.setText(_translate("MainWindow", "Next Leg"))
        self.leg_next.setShortcut(_translate("MainWindow", ">, Ctrl+M"))
        self.setup_info.setTitle(_translate("MainWindow", "Setup Information"))
        self.label.setText(_translate("MainWindow", "Flight Plan:"))
        self.flight_plan_filename.setText(_translate("MainWindow", "No Flight Plan Loaded!"))
        self.label_2.setText(_translate("MainWindow", "Director Log:"))
        self.txt_log_output_name.setText(_translate("MainWindow", "No Output Filename!"))
        self.label_4.setText(_translate("MainWindow", "Data Log:"))
        self.txt_data_log_save_file.setText(_translate("MainWindow", "No Output Filename!"))
        self.label_3.setText(_translate("MainWindow", "Data Location:"))
        self.txt_data_log_dir.setText(_translate("MainWindow", "No Directory Chosen to Scan!"))
        self.instrument_label.setText(_translate("MainWindow", "Instrument: "))
        self.instrument_text.setText(_translate("MainWindow", "No Instrument Set!"))
        self.LegTimers.setTitle(_translate("MainWindow", "Leg Timers"))
        self.txt_leg_timer.setText(_translate("MainWindow", "+00:00:00"))
        self.leg_timer_stop.setText(_translate("MainWindow", "Stop"))
        self.leg_timer_start.setText(_translate("MainWindow", "Start"))
        self.sub_minute.setText(_translate("MainWindow", "-1 Minute"))
        self.add_minute.setText(_translate("MainWindow", "+1 Minute"))
        self.leg_timer_reset.setText(_translate("MainWindow", "Reset"))
        self.time_select_remaining.setText(_translate("MainWindow", "Time Remaining"))
        self.time_select_elapsed.setText(_translate("MainWindow", "Time Elapsed"))
        self.leg_duration.setToolTip(_translate("MainWindow", "HH:MM:SS"))
        self.leg_duration.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.txt_leg_duration.setText(_translate("MainWindow", "Leg Duration"))
        self.groupBox_3.setTitle(_translate("MainWindow", "From Flight Plan"))
        self.label_5.setText(_translate("MainWindow", "Leg Start (UTC)"))
        self.label_6.setText(_translate("MainWindow", "Leg Duration"))

