# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FITSKeywordPanel.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FITSKWDialog(object):
    def setupUi(self, FITSKWDialog):
        FITSKWDialog.setObjectName(_fromUtf8("FITSKWDialog"))
        FITSKWDialog.resize(710, 502)
        FITSKWDialog.setSizeGripEnabled(True)
        FITSKWDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(FITSKWDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_4 = QtGui.QWidget(FITSKWDialog)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 0, 1, 1)
        self.fitskw_dialogbutts = QtGui.QDialogButtonBox(self.widget_4)
        self.fitskw_dialogbutts.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.fitskw_dialogbutts.setObjectName(_fromUtf8("fitskw_dialogbutts"))
        self.gridLayout_13.addWidget(self.fitskw_dialogbutts, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 24, 0, 1, 2)
        self.widget = QtGui.QWidget(FITSKWDialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fitskw_hdu = QtGui.QSpinBox(self.widget)
        self.fitskw_hdu.setAlignment(QtCore.Qt.AlignCenter)
        self.fitskw_hdu.setSuffix(_fromUtf8(""))
        self.fitskw_hdu.setObjectName(_fromUtf8("fitskw_hdu"))
        self.gridLayout_3.addWidget(self.fitskw_hdu, 0, 2, 1, 1)
        self.fitskw_remove = QtGui.QPushButton(self.widget)
        self.fitskw_remove.setObjectName(_fromUtf8("fitskw_remove"))
        self.gridLayout_3.addWidget(self.fitskw_remove, 3, 0, 1, 3)
        self.fitskw_loadlist = QtGui.QPushButton(self.widget)
        self.fitskw_loadlist.setObjectName(_fromUtf8("fitskw_loadlist"))
        self.gridLayout_3.addWidget(self.fitskw_loadlist, 6, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.txt_hduchooser = QtGui.QLabel(self.widget)
        self.txt_hduchooser.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_hduchooser.setObjectName(_fromUtf8("txt_hduchooser"))
        self.gridLayout_3.addWidget(self.txt_hduchooser, 0, 0, 1, 2)
        self.fitskw_add = QtGui.QPushButton(self.widget)
        self.fitskw_add.setDefault(False)
        self.fitskw_add.setObjectName(_fromUtf8("fitskw_add"))
        self.gridLayout_3.addWidget(self.fitskw_add, 2, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)
        self.txt_fitskw_status = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.txt_fitskw_status.setFont(font)
        self.txt_fitskw_status.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fitskw_status.setObjectName(_fromUtf8("txt_fitskw_status"))
        self.gridLayout_3.addWidget(self.txt_fitskw_status, 7, 0, 1, 1)
        self.fitskw_savelist = QtGui.QPushButton(self.widget)
        self.fitskw_savelist.setObjectName(_fromUtf8("fitskw_savelist"))
        self.gridLayout_3.addWidget(self.fitskw_savelist, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.fitskw_listing = QtGui.QListWidget(FITSKWDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fitskw_listing.setFont(font)
        self.fitskw_listing.setDragEnabled(True)
        self.fitskw_listing.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.fitskw_listing.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fitskw_listing.setSelectionRectVisible(True)
        self.fitskw_listing.setObjectName(_fromUtf8("fitskw_listing"))
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        self.gridLayout.addWidget(self.fitskw_listing, 1, 0, 3, 1)
        self.txt_fitskw_hint = QtGui.QLabel(FITSKWDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.txt_fitskw_hint.setFont(font)
        self.txt_fitskw_hint.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fitskw_hint.setObjectName(_fromUtf8("txt_fitskw_hint"))
        self.gridLayout.addWidget(self.txt_fitskw_hint, 4, 0, 1, 1)

        self.retranslateUi(FITSKWDialog)
        QtCore.QMetaObject.connectSlotsByName(FITSKWDialog)

    def retranslateUi(self, FITSKWDialog):
        FITSKWDialog.setWindowTitle(_translate("FITSKWDialog", "FITS Keyword and HDU Selector", None))
        self.fitskw_remove.setText(_translate("FITSKWDialog", "Remove Keyword", None))
        self.fitskw_loadlist.setText(_translate("FITSKWDialog", "Load List ...", None))
        self.txt_hduchooser.setText(_translate("FITSKWDialog", "HDU to Search for Keywords (0 indexed)", None))
        self.fitskw_add.setText(_translate("FITSKWDialog", "Add Keyword", None))
        self.txt_fitskw_status.setText(_translate("FITSKWDialog", "No file loaded or saved ...", None))
        self.fitskw_savelist.setText(_translate("FITSKWDialog", "Save List ...", None))
        __sortingEnabled = self.fitskw_listing.isSortingEnabled()
        self.fitskw_listing.setSortingEnabled(False)
        item = self.fitskw_listing.item(0)
        item.setText(_translate("FITSKWDialog", "DATE-OBS", None))
        item = self.fitskw_listing.item(1)
        item.setText(_translate("FITSKWDialog", "OBS_ID", None))
        item = self.fitskw_listing.item(2)
        item.setText(_translate("FITSKWDialog", "SPECTEL1", None))
        item = self.fitskw_listing.item(3)
        item.setText(_translate("FITSKWDialog", "SPECTEL2", None))
        item = self.fitskw_listing.item(4)
        item.setText(_translate("FITSKWDialog", "MISSN-ID", None))
        item = self.fitskw_listing.item(5)
        item.setText(_translate("FITSKWDialog", "DATASRC", None))
        item = self.fitskw_listing.item(6)
        item.setText(_translate("FITSKWDialog", "INSTRUME", None))
        self.fitskw_listing.setSortingEnabled(__sortingEnabled)
        self.txt_fitskw_hint.setText(_translate("FITSKWDialog", "Note: Drag and Drop Items to Reorder", None))

