#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

import logging
import logging.config
#import logging.handlers
import os
import SOFIACruiseTools.Director.SOFIACruiseDirector as cruise

if __name__=='__main__':

    log_loc = os.path.expanduser('~/.cruiseDirector')
    runlog_loc = os.path.join(log_loc, 'runtime_logs')
    perflog_loc = os.path.join(log_loc, 'performance_logs')
    
    for loc in [log_loc, runlog_loc, perflog_loc]:
        if not os.path.isdir(loc):
            os.makedirs(loc)

    logconfig = os.path.join(os.path.dirname(__file__), 'log.conf')
    logging.config.fileConfig(logconfig)
    logger = logging.getLogger('default')
    loggerp = logging.getLogger('perform')

    # This is hacky as all get out. It gets around
    # permissions issues by giving the log file
    # universal read/write permissions.
    logpath = logger.handlers[0].baseFilename
    os.chmod(logpath, 0o666)
    logpath = loggerp.handlers[0].baseFilename
    os.chmod(logpath, 0o666)

    logger.info('Starting Cruise Director')

    #cruise.main(logger)
    cruise.main()
