# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SOFIACruiseDirectorPanel.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(921, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LegInformation = QtGui.QGroupBox(self.centralwidget)
        self.LegInformation.setObjectName(_fromUtf8("LegInformation"))
        self.gridLayout_4 = QtGui.QGridLayout(self.LegInformation)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.flightplan_openfile = QtGui.QPushButton(self.LegInformation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flightplan_openfile.sizePolicy().hasHeightForWidth())
        self.flightplan_openfile.setSizePolicy(sizePolicy)
        self.flightplan_openfile.setAutoDefault(True)
        self.flightplan_openfile.setObjectName(_fromUtf8("flightplan_openfile"))
        self.gridLayout_4.addWidget(self.flightplan_openfile, 0, 1, 1, 1)
        self.set_landingFP = QtGui.QCheckBox(self.LegInformation)
        self.set_landingFP.setChecked(True)
        self.set_landingFP.setObjectName(_fromUtf8("set_landingFP"))
        self.gridLayout_4.addWidget(self.set_landingFP, 2, 0, 1, 1)
        self.leg_details = QtGui.QWidget(self.LegInformation)
        self.leg_details.setObjectName(_fromUtf8("leg_details"))
        self.gridLayout_6 = QtGui.QGridLayout(self.leg_details)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.txt_target = QtGui.QLabel(self.leg_details)
        self.txt_target.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_target.sizePolicy().hasHeightForWidth())
        self.txt_target.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_target.setFont(font)
        self.txt_target.setLineWidth(1)
        self.txt_target.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_target.setObjectName(_fromUtf8("txt_target"))
        self.gridLayout_6.addWidget(self.txt_target, 2, 0, 1, 1)
        self.txt_rof = QtGui.QLabel(self.leg_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_rof.sizePolicy().hasHeightForWidth())
        self.txt_rof.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_rof.setFont(font)
        self.txt_rof.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_rof.setObjectName(_fromUtf8("txt_rof"))
        self.gridLayout_6.addWidget(self.txt_rof, 4, 0, 1, 1)
        self.txt_leg = QtGui.QLabel(self.leg_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_leg.sizePolicy().hasHeightForWidth())
        self.txt_leg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_leg.setFont(font)
        self.txt_leg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_leg.setObjectName(_fromUtf8("txt_leg"))
        self.gridLayout_6.addWidget(self.txt_leg, 1, 0, 1, 1)
        self.leg_target = QtGui.QLabel(self.leg_details)
        self.leg_target.setText(_fromUtf8(""))
        self.leg_target.setObjectName(_fromUtf8("leg_target"))
        self.gridLayout_6.addWidget(self.leg_target, 2, 1, 1, 1)
        self.leg_obsblock = QtGui.QLabel(self.leg_details)
        self.leg_obsblock.setText(_fromUtf8(""))
        self.leg_obsblock.setObjectName(_fromUtf8("leg_obsblock"))
        self.gridLayout_6.addWidget(self.leg_obsblock, 5, 1, 1, 1)
        self.leg_elevation = QtGui.QLabel(self.leg_details)
        self.leg_elevation.setText(_fromUtf8(""))
        self.leg_elevation.setObjectName(_fromUtf8("leg_elevation"))
        self.gridLayout_6.addWidget(self.leg_elevation, 3, 1, 1, 1)
        self.leg_rofrofrt = QtGui.QLabel(self.leg_details)
        self.leg_rofrofrt.setText(_fromUtf8(""))
        self.leg_rofrofrt.setObjectName(_fromUtf8("leg_rofrofrt"))
        self.gridLayout_6.addWidget(self.leg_rofrofrt, 4, 1, 1, 1)
        self.txt_elevation = QtGui.QLabel(self.leg_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_elevation.sizePolicy().hasHeightForWidth())
        self.txt_elevation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_elevation.setFont(font)
        self.txt_elevation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_elevation.setObjectName(_fromUtf8("txt_elevation"))
        self.gridLayout_6.addWidget(self.txt_elevation, 3, 0, 1, 1)
        self.leg_number = QtGui.QLabel(self.leg_details)
        self.leg_number.setText(_fromUtf8(""))
        self.leg_number.setObjectName(_fromUtf8("leg_number"))
        self.gridLayout_6.addWidget(self.leg_number, 1, 1, 1, 1)
        self.txt_obsplan = QtGui.QLabel(self.leg_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_obsplan.sizePolicy().hasHeightForWidth())
        self.txt_obsplan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_obsplan.setFont(font)
        self.txt_obsplan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_obsplan.setObjectName(_fromUtf8("txt_obsplan"))
        self.gridLayout_6.addWidget(self.txt_obsplan, 5, 0, 1, 1)
        self.gridLayout_4.addWidget(self.leg_details, 3, 0, 1, 2)
        self.flightplan_filename = QtGui.QLabel(self.LegInformation)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.flightplan_filename.setFont(font)
        self.flightplan_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.flightplan_filename.setObjectName(_fromUtf8("flightplan_filename"))
        self.gridLayout_4.addWidget(self.flightplan_filename, 0, 0, 1, 1)
        self.landing_time = QtGui.QDateTimeEdit(self.LegInformation)
        self.landing_time.setAlignment(QtCore.Qt.AlignCenter)
        self.landing_time.setObjectName(_fromUtf8("landing_time"))
        self.gridLayout_4.addWidget(self.landing_time, 2, 1, 1, 1)
        self.takeoff_time = QtGui.QDateTimeEdit(self.LegInformation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeoff_time.sizePolicy().hasHeightForWidth())
        self.takeoff_time.setSizePolicy(sizePolicy)
        self.takeoff_time.setAlignment(QtCore.Qt.AlignCenter)
        self.takeoff_time.setObjectName(_fromUtf8("takeoff_time"))
        self.gridLayout_4.addWidget(self.takeoff_time, 1, 1, 1, 1)
        self.leg_next = QtGui.QPushButton(self.LegInformation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_next.sizePolicy().hasHeightForWidth())
        self.leg_next.setSizePolicy(sizePolicy)
        self.leg_next.setObjectName(_fromUtf8("leg_next"))
        self.gridLayout_4.addWidget(self.leg_next, 4, 1, 1, 1)
        self.set_takeoffFP = QtGui.QCheckBox(self.LegInformation)
        self.set_takeoffFP.setChecked(True)
        self.set_takeoffFP.setObjectName(_fromUtf8("set_takeoffFP"))
        self.gridLayout_4.addWidget(self.set_takeoffFP, 1, 0, 1, 1)
        self.leg_previous = QtGui.QPushButton(self.LegInformation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_previous.sizePolicy().hasHeightForWidth())
        self.leg_previous.setSizePolicy(sizePolicy)
        self.leg_previous.setObjectName(_fromUtf8("leg_previous"))
        self.gridLayout_4.addWidget(self.leg_previous, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.LegInformation, 0, 0, 3, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.set_landing_time = QtGui.QPushButton(self.groupBox)
        self.set_landing_time.setCheckable(False)
        self.set_landing_time.setFlat(False)
        self.set_landing_time.setObjectName(_fromUtf8("set_landing_time"))
        self.gridLayout_7.addWidget(self.set_landing_time, 1, 0, 1, 1)
        self.txt_ttl = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Digital-7"))
        font.setPointSize(60)
        self.txt_ttl.setFont(font)
        self.txt_ttl.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_ttl.setObjectName(_fromUtf8("txt_ttl"))
        self.gridLayout_7.addWidget(self.txt_ttl, 1, 1, 1, 1)
        self.set_takeoff_time = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_takeoff_time.sizePolicy().hasHeightForWidth())
        self.set_takeoff_time.setSizePolicy(sizePolicy)
        self.set_takeoff_time.setObjectName(_fromUtf8("set_takeoff_time"))
        self.gridLayout_7.addWidget(self.set_takeoff_time, 0, 0, 1, 1)
        self.txt_met = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Digital-7"))
        font.setPointSize(60)
        self.txt_met.setFont(font)
        self.txt_met.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_met.setObjectName(_fromUtf8("txt_met"))
        self.gridLayout_7.addWidget(self.txt_met, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.LegTimers = QtGui.QGroupBox(self.centralwidget)
        self.LegTimers.setObjectName(_fromUtf8("LegTimers"))
        self.gridLayout_2 = QtGui.QGridLayout(self.LegTimers)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.LegTimers)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.widget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.leg_timer_stop = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_timer_stop.sizePolicy().hasHeightForWidth())
        self.leg_timer_stop.setSizePolicy(sizePolicy)
        self.leg_timer_stop.setObjectName(_fromUtf8("leg_timer_stop"))
        self.gridLayout_8.addWidget(self.leg_timer_stop, 0, 1, 1, 1)
        self.leg_timer_reset = QtGui.QPushButton(self.widget)
        self.leg_timer_reset.setObjectName(_fromUtf8("leg_timer_reset"))
        self.gridLayout_8.addWidget(self.leg_timer_reset, 1, 0, 1, 2)
        self.leg_timer_start = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leg_timer_start.sizePolicy().hasHeightForWidth())
        self.leg_timer_start.setSizePolicy(sizePolicy)
        self.leg_timer_start.setObjectName(_fromUtf8("leg_timer_start"))
        self.gridLayout_8.addWidget(self.leg_timer_start, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 3, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.LegTimers)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.time_select_remaining = QtGui.QRadioButton(self.widget_2)
        self.time_select_remaining.setChecked(True)
        self.time_select_remaining.setObjectName(_fromUtf8("time_select_remaining"))
        self.gridLayout_9.addWidget(self.time_select_remaining, 0, 0, 1, 1)
        self.time_select_elapsed = QtGui.QRadioButton(self.widget_2)
        self.time_select_elapsed.setChecked(False)
        self.time_select_elapsed.setObjectName(_fromUtf8("time_select_elapsed"))
        self.gridLayout_9.addWidget(self.time_select_elapsed, 0, 1, 1, 1)
        self.leg_duration = QtGui.QTimeEdit(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leg_duration.setFont(font)
        self.leg_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.leg_duration.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.leg_duration.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.leg_duration.setTimeSpec(QtCore.Qt.LocalTime)
        self.leg_duration.setObjectName(_fromUtf8("leg_duration"))
        self.gridLayout_9.addWidget(self.leg_duration, 3, 0, 1, 2)
        self.txt_leg_duration = QtGui.QLabel(self.widget_2)
        self.txt_leg_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_leg_duration.setObjectName(_fromUtf8("txt_leg_duration"))
        self.gridLayout_9.addWidget(self.txt_leg_duration, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget_2, 2, 0, 1, 1)
        self.txt_leg_timer = QtGui.QLabel(self.LegTimers)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Digital-7"))
        font.setPointSize(60)
        self.txt_leg_timer.setFont(font)
        self.txt_leg_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_leg_timer.setObjectName(_fromUtf8("txt_leg_timer"))
        self.gridLayout_2.addWidget(self.txt_leg_timer, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.LegTimers, 0, 1, 3, 3)
        self.TimesWorld = QtGui.QGroupBox(self.centralwidget)
        self.TimesWorld.setObjectName(_fromUtf8("TimesWorld"))
        self.gridLayout_5 = QtGui.QGridLayout(self.TimesWorld)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.txt_utc = QtGui.QLabel(self.TimesWorld)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Digital-7"))
        font.setPointSize(60)
        font.setItalic(True)
        self.txt_utc.setFont(font)
        self.txt_utc.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_utc.setObjectName(_fromUtf8("txt_utc"))
        self.gridLayout_5.addWidget(self.txt_utc, 0, 0, 1, 1)
        self.txt_localtime = QtGui.QLabel(self.TimesWorld)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Digital-7"))
        font.setPointSize(60)
        font.setItalic(True)
        self.txt_localtime.setFont(font)
        self.txt_localtime.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_localtime.setObjectName(_fromUtf8("txt_localtime"))
        self.gridLayout_5.addWidget(self.txt_localtime, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.TimesWorld, 3, 1, 1, 3)
        self.Log = QtGui.QGroupBox(self.centralwidget)
        self.Log.setObjectName(_fromUtf8("Log"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Log)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.log_inputline = QtGui.QLineEdit(self.Log)
        self.log_inputline.setObjectName(_fromUtf8("log_inputline"))
        self.gridLayout_3.addWidget(self.log_inputline, 3, 0, 1, 1)
        self.log_display = QtGui.QTextEdit(self.Log)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_display.sizePolicy().hasHeightForWidth())
        self.log_display.setSizePolicy(sizePolicy)
        self.log_display.setReadOnly(True)
        self.log_display.setObjectName(_fromUtf8("log_display"))
        self.gridLayout_3.addWidget(self.log_display, 0, 0, 1, 4)
        self.log_post = QtGui.QPushButton(self.Log)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_post.sizePolicy().hasHeightForWidth())
        self.log_post.setSizePolicy(sizePolicy)
        self.log_post.setObjectName(_fromUtf8("log_post"))
        self.gridLayout_3.addWidget(self.log_post, 3, 1, 1, 3)
        self.gridLayout.addWidget(self.Log, 4, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFIA Science Cruise Director", None))
        self.LegInformation.setTitle(_translate("MainWindow", "Flight Plan Information", None))
        self.flightplan_openfile.setText(_translate("MainWindow", "Open Flight Plan", None))
        self.flightplan_openfile.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.set_landingFP.setText(_translate("MainWindow", "Set Landing from Flight Plan", None))
        self.txt_target.setText(_translate("MainWindow", "Target:", None))
        self.txt_rof.setText(_translate("MainWindow", "ROF | ROFrate:", None))
        self.txt_leg.setText(_translate("MainWindow", "Leg:", None))
        self.txt_elevation.setText(_translate("MainWindow", "Elevation Range:", None))
        self.txt_obsplan.setText(_translate("MainWindow", "ObsPlan:", None))
        self.flightplan_filename.setText(_translate("MainWindow", "No Flight Plan Loaded!", None))
        self.landing_time.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy HH:mm:ss", None))
        self.takeoff_time.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy HH:mm:ss", None))
        self.leg_next.setText(_translate("MainWindow", "Next Leg", None))
        self.leg_next.setShortcut(_translate("MainWindow", ">, Ctrl+M", None))
        self.set_takeoffFP.setText(_translate("MainWindow", "Set Takeoff from Flight Plan", None))
        self.leg_previous.setText(_translate("MainWindow", "Previous Leg", None))
        self.leg_previous.setShortcut(_translate("MainWindow", "<, Ctrl+N", None))
        self.groupBox.setTitle(_translate("MainWindow", "Current Flight Progress", None))
        self.set_landing_time.setText(_translate("MainWindow", "Start", None))
        self.txt_ttl.setText(_translate("MainWindow", "TTL", None))
        self.set_takeoff_time.setText(_translate("MainWindow", "Start", None))
        self.txt_met.setText(_translate("MainWindow", "MET", None))
        self.LegTimers.setTitle(_translate("MainWindow", "Leg Timers", None))
        self.leg_timer_stop.setText(_translate("MainWindow", "Stop", None))
        self.leg_timer_reset.setText(_translate("MainWindow", "Reset", None))
        self.leg_timer_start.setText(_translate("MainWindow", "Start", None))
        self.time_select_remaining.setText(_translate("MainWindow", "Time Remaining", None))
        self.time_select_elapsed.setText(_translate("MainWindow", "Time Elapsed", None))
        self.leg_duration.setToolTip(_translate("MainWindow", "HH:MM:SS", None))
        self.leg_duration.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.txt_leg_duration.setText(_translate("MainWindow", "Leg Duration", None))
        self.txt_leg_timer.setText(_translate("MainWindow", "+00:00:00", None))
        self.TimesWorld.setTitle(_translate("MainWindow", "World Times", None))
        self.txt_utc.setText(_translate("MainWindow", "UTC", None))
        self.txt_localtime.setText(_translate("MainWindow", "LOCAL", None))
        self.Log.setTitle(_translate("MainWindow", "Cruise Director\'s Log", None))
        self.log_display.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.log_post.setText(_translate("MainWindow", "Post", None))

