# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEditUserName = QtWidgets.QLineEdit(self.widget)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout_6.addWidget(self.lineEditUserName, 0, 1, 1, 1)
        self.labelSeriesTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSeriesTitle.setFont(font)
        self.labelSeriesTitle.setObjectName("labelSeriesTitle")
        self.gridLayout_6.addWidget(self.labelSeriesTitle, 0, 3, 1, 1)
        self.lineEditSeriesTitle = QtWidgets.QLineEdit(self.widget)
        self.lineEditSeriesTitle.setObjectName("lineEditSeriesTitle")
        self.gridLayout_6.addWidget(self.lineEditSeriesTitle, 0, 4, 1, 1)
        self.checkBoxAutosortFlights = QtWidgets.QCheckBox(self.widget)
        self.checkBoxAutosortFlights.setChecked(True)
        self.checkBoxAutosortFlights.setObjectName("checkBoxAutosortFlights")
        self.gridLayout_6.addWidget(self.checkBoxAutosortFlights, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        self.labelUsername = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout_6.addWidget(self.labelUsername, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 5, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 4)
        self.pushButtonRemoveFlight = QtWidgets.QPushButton(self.frame)
        self.pushButtonRemoveFlight.setObjectName("pushButtonRemoveFlight")
        self.gridLayout_3.addWidget(self.pushButtonRemoveFlight, 4, 3, 1, 1)
        self.labelSeriesFlightList = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSeriesFlightList.setFont(font)
        self.labelSeriesFlightList.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSeriesFlightList.setObjectName("labelSeriesFlightList")
        self.gridLayout_3.addWidget(self.labelSeriesFlightList, 1, 0, 1, 4)
        self.tableWidgetFlightBasics = DragDropTable(self.frame)
        self.tableWidgetFlightBasics.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidgetFlightBasics.setObjectName("tableWidgetFlightBasics")
        self.tableWidgetFlightBasics.setColumnCount(0)
        self.tableWidgetFlightBasics.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetFlightBasics, 3, 0, 1, 4)
        self.pushButtonAddFlight = QtWidgets.QPushButton(self.frame)
        self.pushButtonAddFlight.setObjectName("pushButtonAddFlight")
        self.gridLayout_3.addWidget(self.pushButtonAddFlight, 4, 0, 1, 1)
        self.pushButtonMoveUp = QtWidgets.QPushButton(self.frame)
        self.pushButtonMoveUp.setObjectName("pushButtonMoveUp")
        self.gridLayout_3.addWidget(self.pushButtonMoveUp, 4, 1, 1, 1)
        self.pushButtonMoveDown = QtWidgets.QPushButton(self.frame)
        self.pushButtonMoveDown.setObjectName("pushButtonMoveDown")
        self.gridLayout_3.addWidget(self.pushButtonMoveDown, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 2, 2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 316))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelWarnings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelWarnings.setFont(font)
        self.labelWarnings.setObjectName("labelWarnings")
        self.gridLayout_5.addWidget(self.labelWarnings, 1, 0, 1, 1)
        self.labelErrors = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelErrors.setFont(font)
        self.labelErrors.setObjectName("labelErrors")
        self.gridLayout_5.addWidget(self.labelErrors, 2, 0, 1, 1)
        self.labelNotes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNotes.setFont(font)
        self.labelNotes.setObjectName("labelNotes")
        self.gridLayout_5.addWidget(self.labelNotes, 0, 0, 1, 1)
        self.labelTips = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTips.setFont(font)
        self.labelTips.setObjectName("labelTips")
        self.gridLayout_5.addWidget(self.labelTips, 3, 0, 1, 1)
        self.textEditNotes = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditNotes.setObjectName("textEditNotes")
        self.gridLayout_5.addWidget(self.textEditNotes, 0, 1, 1, 1)
        self.textEditWarnings = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditWarnings.setObjectName("textEditWarnings")
        self.gridLayout_5.addWidget(self.textEditWarnings, 1, 1, 1, 1)
        self.textEditErrors = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditErrors.setObjectName("textEditErrors")
        self.gridLayout_5.addWidget(self.textEditErrors, 2, 1, 1, 1)
        self.textEditTips = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditTips.setObjectName("textEditTips")
        self.gridLayout_5.addWidget(self.textEditTips, 3, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 4, 0, 1, 2)
        self.labelCurrentFlight = QtWidgets.QLabel(self.frame_3)
        self.labelCurrentFlight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentFlight.setObjectName("labelCurrentFlight")
        self.gridLayout_4.addWidget(self.labelCurrentFlight, 0, 0, 1, 2)
        self.pushButtonPrevFlight = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonPrevFlight.setObjectName("pushButtonPrevFlight")
        self.gridLayout_4.addWidget(self.pushButtonPrevFlight, 3, 1, 1, 1)
        self.pushButtonNextFlight = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonNextFlight.setObjectName("pushButtonNextFlight")
        self.gridLayout_4.addWidget(self.pushButtonNextFlight, 3, 0, 1, 1)
        self.tableWidgetCurrentFlight = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidgetCurrentFlight.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidgetCurrentFlight.setObjectName("tableWidgetCurrentFlight")
        self.tableWidgetCurrentFlight.setColumnCount(0)
        self.tableWidgetCurrentFlight.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetCurrentFlight, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFIA Cruise Reviewer"))
        self.labelSeriesTitle.setText(_translate("MainWindow", "Series Title:"))
        self.checkBoxAutosortFlights.setText(_translate("MainWindow", "Autosort Flight Dates"))
        self.labelUsername.setText(_translate("MainWindow", "Username:"))
        self.pushButtonRemoveFlight.setText(_translate("MainWindow", "Remove Selected"))
        self.labelSeriesFlightList.setText(_translate("MainWindow", "Series Overview"))
        self.pushButtonAddFlight.setText(_translate("MainWindow", "Add Flight(s)"))
        self.pushButtonMoveUp.setText(_translate("MainWindow", "Move Up"))
        self.pushButtonMoveDown.setText(_translate("MainWindow", "Move Down"))
        self.labelWarnings.setText(_translate("MainWindow", "Warnings:"))
        self.labelErrors.setText(_translate("MainWindow", "Errors:"))
        self.labelNotes.setText(_translate("MainWindow", "Notes:"))
        self.labelTips.setText(_translate("MainWindow", "Tips:"))
        self.labelCurrentFlight.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonPrevFlight.setText(_translate("MainWindow", "Previous Flight"))
        self.pushButtonNextFlight.setText(_translate("MainWindow", "Next Flight"))

from .dragdroptable import DragDropTable
