# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 1, 1, 1)
        self.pushButtonRemoveFlight = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonRemoveFlight.setObjectName("pushButtonRemoveFlight")
        self.gridLayout_2.addWidget(self.pushButtonRemoveFlight, 5, 2, 1, 1)
        self.labelSeriesTitle = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSeriesTitle.setFont(font)
        self.labelSeriesTitle.setObjectName("labelSeriesTitle")
        self.gridLayout_2.addWidget(self.labelSeriesTitle, 1, 0, 1, 1)
        self.pushButtonAddFlight = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAddFlight.setObjectName("pushButtonAddFlight")
        self.gridLayout_2.addWidget(self.pushButtonAddFlight, 5, 0, 1, 1)
        self.labelUsername = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout_2.addWidget(self.labelUsername, 0, 0, 1, 1)
        self.labelSeriesFlightList = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSeriesFlightList.setFont(font)
        self.labelSeriesFlightList.setObjectName("labelSeriesFlightList")
        self.gridLayout_2.addWidget(self.labelSeriesFlightList, 2, 0, 1, 3)
        self.pushButtonParseList = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonParseList.setObjectName("pushButtonParseList")
        self.gridLayout_2.addWidget(self.pushButtonParseList, 5, 4, 1, 1)
        self.listWidgetFlights = QtWidgets.QListWidget(self.groupBox)
        self.listWidgetFlights.setObjectName("listWidgetFlights")
        self.gridLayout_2.addWidget(self.listWidgetFlights, 3, 0, 1, 5)
        self.lineEditSeriesTitle = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSeriesTitle.setObjectName("lineEditSeriesTitle")
        self.gridLayout_2.addWidget(self.lineEditSeriesTitle, 1, 1, 1, 4)
        self.lineEditUserName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout_2.addWidget(self.lineEditUserName, 0, 1, 1, 4)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelFlightBasics = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFlightBasics.setFont(font)
        self.labelFlightBasics.setObjectName("labelFlightBasics")
        self.gridLayout_3.addWidget(self.labelFlightBasics, 0, 0, 1, 1)
        self.tableWidgetFlightBasics = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidgetFlightBasics.setObjectName("tableWidgetFlightBasics")
        self.tableWidgetFlightBasics.setColumnCount(0)
        self.tableWidgetFlightBasics.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetFlightBasics, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 742, 316))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelWarnings = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelWarnings.setFont(font)
        self.labelWarnings.setObjectName("labelWarnings")
        self.gridLayout_5.addWidget(self.labelWarnings, 1, 0, 1, 1)
        self.labelErrors = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelErrors.setFont(font)
        self.labelErrors.setObjectName("labelErrors")
        self.gridLayout_5.addWidget(self.labelErrors, 2, 0, 1, 1)
        self.labelNotes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNotes.setFont(font)
        self.labelNotes.setObjectName("labelNotes")
        self.gridLayout_5.addWidget(self.labelNotes, 0, 0, 1, 1)
        self.labelTips = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTips.setFont(font)
        self.labelTips.setObjectName("labelTips")
        self.gridLayout_5.addWidget(self.labelTips, 3, 0, 1, 1)
        self.textEditNotes = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditNotes.setObjectName("textEditNotes")
        self.gridLayout_5.addWidget(self.textEditNotes, 0, 1, 1, 1)
        self.textEditWarnings = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditWarnings.setObjectName("textEditWarnings")
        self.gridLayout_5.addWidget(self.textEditWarnings, 1, 1, 1, 1)
        self.textEditErrors = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditErrors.setObjectName("textEditErrors")
        self.gridLayout_5.addWidget(self.textEditErrors, 2, 1, 1, 1)
        self.textEditTips = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditTips.setObjectName("textEditTips")
        self.gridLayout_5.addWidget(self.textEditTips, 3, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 4, 0, 1, 2)
        self.labelCurrentFlight = QtWidgets.QLabel(self.groupBox_3)
        self.labelCurrentFlight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentFlight.setObjectName("labelCurrentFlight")
        self.gridLayout_4.addWidget(self.labelCurrentFlight, 0, 0, 1, 2)
        self.pushButtonPrevFlight = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonPrevFlight.setObjectName("pushButtonPrevFlight")
        self.gridLayout_4.addWidget(self.pushButtonPrevFlight, 3, 1, 1, 1)
        self.pushButtonNextFlight = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonNextFlight.setObjectName("pushButtonNextFlight")
        self.gridLayout_4.addWidget(self.pushButtonNextFlight, 3, 0, 1, 1)
        self.tableWidgetCurrentFlight = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidgetCurrentFlight.setObjectName("tableWidgetCurrentFlight")
        self.tableWidgetCurrentFlight.setColumnCount(0)
        self.tableWidgetCurrentFlight.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetCurrentFlight, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFIA Cruise Reviewer"))
        self.pushButtonRemoveFlight.setText(_translate("MainWindow", "Remove"))
        self.labelSeriesTitle.setText(_translate("MainWindow", "Series Title:"))
        self.pushButtonAddFlight.setText(_translate("MainWindow", "Add"))
        self.labelUsername.setText(_translate("MainWindow", "Username:"))
        self.labelSeriesFlightList.setText(_translate("MainWindow", "Flights in the Series:"))
        self.pushButtonParseList.setText(_translate("MainWindow", "Parse"))
        self.labelFlightBasics.setText(_translate("MainWindow", "Flight Basics"))
        self.labelWarnings.setText(_translate("MainWindow", "Warnings:"))
        self.labelErrors.setText(_translate("MainWindow", "Errors:"))
        self.labelNotes.setText(_translate("MainWindow", "Notes:"))
        self.labelTips.setText(_translate("MainWindow", "Tips:"))
        self.labelCurrentFlight.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonPrevFlight.setText(_translate("MainWindow", "Previous Flight"))
        self.pushButtonNextFlight.setText(_translate("MainWindow", "Next Flight"))

