# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidgetIO = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetIO.setObjectName("tabWidgetIO")
        self.tabInput = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabInput.sizePolicy().hasHeightForWidth())
        self.tabInput.setSizePolicy(sizePolicy)
        self.tabInput.setAutoFillBackground(True)
        self.tabInput.setObjectName("tabInput")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabInput)
        self.gridLayout_4.setContentsMargins(9, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollAreaInput = QtWidgets.QScrollArea(self.tabInput)
        self.scrollAreaInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaInput.setWidgetResizable(True)
        self.scrollAreaInput.setObjectName("scrollAreaInput")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 765, 447))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEditNotes = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditNotes.setObjectName("plainTextEditNotes")
        self.gridLayout_2.addWidget(self.plainTextEditNotes, 4, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 4, 1, 1)
        self.lineEditGoal = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditGoal.setObjectName("lineEditGoal")
        self.gridLayout_2.addWidget(self.lineEditGoal, 3, 2, 1, 3)
        self.labelAORNotes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAORNotes.setFont(font)
        self.labelAORNotes.setObjectName("labelAORNotes")
        self.gridLayout_2.addWidget(self.labelAORNotes, 7, 0, 1, 1)
        self.labelNotes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNotes.setFont(font)
        self.labelNotes.setObjectName("labelNotes")
        self.gridLayout_2.addWidget(self.labelNotes, 4, 0, 1, 1)
        self.labelAOR = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAOR.setFont(font)
        self.labelAOR.setObjectName("labelAOR")
        self.gridLayout_2.addWidget(self.labelAOR, 5, 0, 1, 1)
        self.labelAORFilename = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelAORFilename.setFont(font)
        self.labelAORFilename.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAORFilename.setObjectName("labelAORFilename")
        self.gridLayout_2.addWidget(self.labelAORFilename, 5, 3, 1, 1)
        self.tableAORSummary = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableAORSummary.setObjectName("tableAORSummary")
        self.gridLayout_2.addWidget(self.tableAORSummary, 6, 0, 1, 5)
        self.buttonAOROpen = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonAOROpen.setObjectName("buttonAOROpen")
        self.gridLayout_2.addWidget(self.buttonAOROpen, 5, 2, 1, 1)
        self.labelLegSummary = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLegSummary.setFont(font)
        self.labelLegSummary.setObjectName("labelLegSummary")
        self.gridLayout_2.addWidget(self.labelLegSummary, 1, 0, 1, 3)
        self.labelGoal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGoal.setFont(font)
        self.labelGoal.setObjectName("labelGoal")
        self.gridLayout_2.addWidget(self.labelGoal, 3, 0, 1, 1)
        self.plainTextEditAORNotes = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditAORNotes.setObjectName("plainTextEditAORNotes")
        self.gridLayout_2.addWidget(self.plainTextEditAORNotes, 8, 0, 1, 5)
        self.labelInputSpacer1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelInputSpacer1.setText("")
        self.labelInputSpacer1.setObjectName("labelInputSpacer1")
        self.gridLayout_2.addWidget(self.labelInputSpacer1, 0, 0, 1, 1)
        self.tableLegSummary = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableLegSummary.setObjectName("tableLegSummary")
        self.gridLayout_2.addWidget(self.tableLegSummary, 2, 0, 1, 5)
        self.scrollAreaInput.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollAreaInput, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.buttonPreviousLeg = QtWidgets.QPushButton(self.tabInput)
        self.buttonPreviousLeg.setObjectName("buttonPreviousLeg")
        self.gridLayout_4.addWidget(self.buttonPreviousLeg, 1, 0, 1, 1)
        self.buttonNextLeg = QtWidgets.QPushButton(self.tabInput)
        self.buttonNextLeg.setObjectName("buttonNextLeg")
        self.gridLayout_4.addWidget(self.buttonNextLeg, 1, 1, 1, 1)
        self.tabWidgetIO.addTab(self.tabInput, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.tabWidgetIO.addTab(self.tabOutput, "")
        self.gridLayout_3.addWidget(self.tabWidgetIO, 4, 0, 1, 1)
        self.topGrid = QtWidgets.QGridLayout()
        self.topGrid.setObjectName("topGrid")
        self.lineEditUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.topGrid.addWidget(self.lineEditUserName, 1, 5, 1, 1)
        self.labelUserName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelUserName.setFont(font)
        self.labelUserName.setObjectName("labelUserName")
        self.topGrid.addWidget(self.labelUserName, 1, 4, 1, 1)
        self.tableFlightPlanSummary = QtWidgets.QTableWidget(self.centralwidget)
        self.tableFlightPlanSummary.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableFlightPlanSummary.setObjectName("tableFlightPlanSummary")
        self.tableFlightPlanSummary.setColumnCount(0)
        self.tableFlightPlanSummary.setRowCount(0)
        self.topGrid.addWidget(self.tableFlightPlanSummary, 3, 0, 1, 6)
        self.labelInstruments = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelInstruments.setFont(font)
        self.labelInstruments.setObjectName("labelInstruments")
        self.topGrid.addWidget(self.labelInstruments, 1, 0, 1, 1)
        self.comboBoxInstruments = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxInstruments.setObjectName("comboBoxInstruments")
        self.topGrid.addWidget(self.comboBoxInstruments, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGrid.addItem(spacerItem1, 1, 3, 1, 1)
        self.labelFlightPlanFilename = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelFlightPlanFilename.setFont(font)
        self.labelFlightPlanFilename.setObjectName("labelFlightPlanFilename")
        self.topGrid.addWidget(self.labelFlightPlanFilename, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topGrid.addItem(spacerItem2, 2, 3, 1, 1)
        self.labelFlightPlanImageFilename = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelFlightPlanImageFilename.setFont(font)
        self.labelFlightPlanImageFilename.setObjectName("labelFlightPlanImageFilename")
        self.topGrid.addWidget(self.labelFlightPlanImageFilename, 2, 4, 1, 2)
        self.gridLayout_3.addLayout(self.topGrid, 0, 0, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Flight_Plan = QtWidgets.QAction(MainWindow)
        self.actionOpen_Flight_Plan.setObjectName("actionOpen_Flight_Plan")
        self.actionChoose_Flight_Plan_Image = QtWidgets.QAction(MainWindow)
        self.actionChoose_Flight_Plan_Image.setObjectName("actionChoose_Flight_Plan_Image")
        self.menuFile.addAction(self.actionOpen_Flight_Plan)
        self.menuFile.addAction(self.actionChoose_Flight_Plan_Image)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetIO.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SOFIA Cruise Planner"))
        self.plainTextEditNotes.setPlainText(_translate("MainWindow", "This is a note.\n"
"It can be multiline.\n"
"It can have **markdown**\n"
"(also it can scroll)"))
        self.lineEditGoal.setText(_translate("MainWindow", "Single line only! No special characters"))
        self.labelAORNotes.setText(_translate("MainWindow", "AOR Notes:"))
        self.labelNotes.setText(_translate("MainWindow", "Notes:"))
        self.labelAOR.setText(_translate("MainWindow", "AOR:"))
        self.labelAORFilename.setText(_translate("MainWindow", "No File Chosen ..."))
        self.buttonAOROpen.setText(_translate("MainWindow", "Open ..."))
        self.labelLegSummary.setText(_translate("MainWindow", "Leg Summary"))
        self.labelGoal.setText(_translate("MainWindow", "Goal:"))
        self.plainTextEditAORNotes.setPlainText(_translate("MainWindow", "This is a note.\n"
"It can be multiline.\n"
"It can have **markdown**\n"
"(also it can scroll)"))
        self.buttonPreviousLeg.setText(_translate("MainWindow", "Previous Leg"))
        self.buttonNextLeg.setText(_translate("MainWindow", "Next Leg"))
        self.tabWidgetIO.setTabText(self.tabWidgetIO.indexOf(self.tabInput), _translate("MainWindow", "Input"))
        self.tabWidgetIO.setTabText(self.tabWidgetIO.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.labelUserName.setText(_translate("MainWindow", "User Name"))
        self.labelInstruments.setText(_translate("MainWindow", "Instrument"))
        self.labelFlightPlanFilename.setText(_translate("MainWindow", "No Flight Plan Chosen ..."))
        self.labelFlightPlanImageFilename.setText(_translate("MainWindow", "No Flight Plan Image Chosen ..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Flight_Plan.setText(_translate("MainWindow", "Open Flight Plan ..."))
        self.actionChoose_Flight_Plan_Image.setText(_translate("MainWindow", "Choose Flight Plan Image ..."))

